version: 1.0
provider:
  name: openfaas
  gateway: https://lucasr.exit.openfaas.pro
functions:
  bot:
    lang: pyslash
    handler: ./bot
    image: theaxer/test-bot:latest
    secrets:
      - slack-api-token
      - slack-signing-secret

